---
- hosts: apache
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      notify:
        - Start Apache Service

  handlers:
    - name: Start Apache Service
      service:
        name: apache2
        state: started
        enabled: true

- hosts: nginx
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      notify:
        - Start Nginx Service

  handlers:
    - name: Start Nginx Service
      service:
        name: nginx
        state: started
        enabled: true
